### ISSUE TITLE
PostgreSQL DB error while installing godojo in Debian OS

### ISSUE THREAD

**Issue by ganesh2183** [DefectDojo/godojo#26]
Installing godojo in Virtualbox VM Debian 10 (guest OS) 

Running the command **./godojo** in console, getting the error message as "ERROR: Unable to run pg_isready to validate PostgreSQL DB status".

**Comment by ganesh2183** [comment]
![Uploading IMG_20210901_191427.jpg…]()

**Comment by ganesh2183** [comment]
![IMG_20210901_191427](https://user-images.githubusercontent.com/41476297/131689552-cff8d044-f8a0-4264-ae84-534f66c43673.jpg)

**Comment by mtesauro** [comment]
If you're not using the latest version of godojo, then the quick solution is to install the postgresql-client-common Debian package, rm -rf /opt/dojo (or the path you chose if different from the default) and re-run godojo.

I remember having this issue before and thought the fix was in the latest release but I could be wrong.

**Comment by mtesauro** [comment]
Going to go ahead and close this one.

**Comment by dmulitsa** [comment]
The same error on Debian Buster with installed `postgresql-client-common` package.
```
./godojo -v
godojo version 1.1.6
```
The same on docker container and AWS EC2 fresh instance
