### ISSUE TITLE
Cannot load io/fs: malformed module path "io/fs": missing dot in first path element

### ISSUE THREAD

**Issue by noloader** [DefectDojo/godojo#31]
I'm trying to build the installer on Ubuntu 20.04.3 LTS, x86_64. I'm using Master. Running `go build` results in:

```text
$ go build
build github.com/mtesauro/godojo: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
```

**Comment by mtesauro** [comment]
What version of go are you using? I'm basically on the same OS as you:

```
$ go version
go version go1.17.3 linux/amd64
$ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
$ pwd
/my/path/defectdojo/godojo
$ go build
$ 
```

prior to updating to 1.17.3 recently, I was running 1.16.3 of Go downloaded for golang.org and manually installed.

FWIW, I've never tried to go build from a URL since I have the code locally - don't think that matters but I've never built godojo that way.

**Comment by mtesauro** [comment]
Also, io/fs came into go around 1.16 so if your `go version` is less than 1.16, that's likely your problem.
