### ISSUE TITLE
SSL not working This site can’t provide a secure connection

### ISSUE THREAD

**Issue by elyeschemengui** [DefectDojo/godojo#41]
Hi team,

I have installed defectdojo and everything is working fine on port 8000.

Actually i want to enable SSL and to make it work on Port 443.

I have imported my cert & key under /etc/ssl/

I have changed thte nginx.conf with the content nginx_TLS.conf and made the following modification

[...]
 server {
    server_tokens off;
    listen 443 ssl;
    server_name mywebsite.com;
    ssl_certificate /etc/ssl/def.crt;
    ssl_certificate_key /etc/ssl/def.key;
[...]

I have modified also on dojo-start like follow
[...] 0.0.0.0:443

But when i run it I get the following error

![image](https://user-images.githubusercontent.com/25328159/159748410-7c4f3ef9-62a4-47bb-a551-7408043c500f.png)

Is there any other files i need to update, to make it work ?

Thanks in advance

**Comment by mtesauro** [comment]
Couple of things here.

godojo's job is to get DefectDojo installed and running on an HTTP port.  Since there's loads of different ways to add TLS to DefefectDojo, those are included in godojo. So the below means godojo did it's job:

> I have installed defectdojo and everything is working fine on port 8000.

The general idea is to put an HTTPS server that answers on 443 as a forward proxy "in front of" DefectDojo listening on 8000
```
 ---------                       -------------                       ------------
| Browser | ---HTTPS on 443---> | Some Server | ---HTTP on 8000---> | DefectDojo |
 ---------                       -------------                       ------------
```

"Some Server" could be Apache, Nginx, Caddy, anything that can be a reverse-proxy and serve TLS/HTTPS connections. what you choose is matter of personal preference.

In your case, I'd change back dojo-start to be 8000 (or for a more secure setup, 127.0.0.1:8000) on [this line](https://github.com/DefectDojo/godojo/blob/master/docs-and-scripts/dojo-start#L26) so that DefectDojo is answering HTTP on 8000.

Then use a Nginx reverse proxy tutorial like the one below to put nginx 'in front' of DefectDojo running TLS/HTTPS:
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

NOTE: The Digital Ocean link above has nginx fronting a service on 8080 - you'll need to change that to 8000 in the tutorial's nginx config examples.

HTH.
