### ISSUE TITLE
Facing error while running Godojo

### ISSUE THREAD

**Issue by Sujitha6496** [DefectDojo/godojo#46]
ERROR: 2022/08/25 05:16:07 - Failed to run OS command cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py makemigrations dojo, error was: exit status 1
OS : Ubuntu 20.04 LTS

**Comment by mtesauro** [comment]
The easiest way to diagnose the issue is to copy paste the command in that error message into the terminal and see what output you get from Linux.

So, for that one, just run the below to get more info on what's going on:
```
cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py makemigrations dojo
```

If it's a DB migration issue, that's probably best to ask on OWASP Slack's #defectdojo see [here](cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py makemigrations dojo)
